modLoader = "javafml"
loaderVersion="[43,)"
license = "MIT License"
[[mods]]
modId = "create_mechanical_teleporter"
version = "${file.jarVersion}"
displayName = "Create Mechanical Teleporter"
logoFile="logo.png"
description = '''
Mechanical Teleporter.
'''

[[dependencies.create_mechanical_teleporter]]
modId = "forge"
mandatory = true
versionRange="[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_mechanical_teleporter]]
modId = "minecraft"
mandatory = true
versionRange="[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_mechanical_teleporter]]
modId = "create"
mandatory = true
versionRange="[0.5.1.h,)"
ordering = "AFTER"
side = "BOTH"

